plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.9.23'
    id 'java-gradle-plugin'
}

group = 'com.interview.thread'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

kotlin {
    jvmToolchain(17)
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    mavenCentral()
    google()
}

dependencies {
    compileOnly 'com.android.tools.build:gradle-api:8.3.0'
    compileOnly 'org.jetbrains.kotlin:kotlin-stdlib:1.9.23'
    implementation 'org.ow2.asm:asm:9.6'
    implementation 'org.ow2.asm:asm-tree:9.6'
    implementation 'org.ow2.asm:asm-commons:9.6'
}

gradlePlugin {
    plugins {
        threadMonitor {
            id = 'com.interview.thread.monitor'
            implementationClass = 'com.interview.thread.plugin.ThreadMonitorPlugin'
        }
    }
}
