//! 构建期脚本 —— 本 Lab 的「加固流水线」真正发生的地方。
//!
//! ─── 它做三件事 ───
//!
//! 1. 调 `algorithms::*::build()`（三个算子的字节码生成器）拿到**明文**容器；
//! 2. 用 ChaCha20 加密容器的载荷（`[20..]`，即常量池 + 字节码），再重算校验和；
//! 3. 把密文写成字节数组字面量，生成 `OUT_DIR/programs.rs`，由 `lib.rs` `include!` 进来。
//!
//! ─── 为什么 build.rs 要 `include!` src 里的文件，而不是自己再写一份 ───
//!
//! ```text
//! include!("src/format.rs")     容器格式 / 操作码 / LEB128   ← 只有一份，VM 与生成器共用
//! include!("src/crypt.rs")      ChaCha20                     ← 只有一份，加解密同源
//! include!("src/asm.rs")        汇编器
//! include!("src/key.rs")        密钥与非名表
//! include!("src/algorithms/…")  三个算子的字节码生成器
//! ```
//!
//! 如果 build.rs 自己抄一份格式定义或 ChaCha20，那么「构建期加密」与「运行期解密」
//! 就有了两个可能漂移的实现 —— 而漂移的后果是运行期解出垃圾字节码，
//! 报个 `BAD_OPCODE` 就完事，排查全在设备上。`include!` 从机制上消灭这种可能。
//!
//! ─── 构建产物里能看到什么 ───
//!
//! `programs.rs` 里是三个**十六进制字面量数组**。这就是加固的全部秘密所在：
//! 拿到 `.so` 的人能看到「有三个程序、各多大、常量池多大」，但看不到任何一条指令。
//! 这是**刻意**的取舍（见 `ISA.md` 第 4 节）：VM 需要明文头才能知道该解密多少字节。

// build.rs 只 `include!` 了 `src/` 的一个子集（格式/汇编器/密码学/密钥/生成器），
// 因此被包含的模块里必然有「本 crate 用不到」的项（如 VM 专用的 `unzigzag`、
// 未被三个算子用到的操作码变体）。这不是缺陷，是刻意的裁剪 —— 直接放行。
#![allow(dead_code, unused_imports)]

use std::env;
use std::fs;
use std::path::Path;

// ─────────────────────────────────────────────────────────────────────────────
// 把 src/ 下的模块原样搬进构建脚本的 crate。
//
// `#[path]` 让 Rust 从指定文件读模块，于是这些源文件同时属于两个 crate
// （构建脚本与发布库），却只有一份源码。注意 `crate::` 的解析：模块都挂在
// 构建脚本根下，与它们在库里被 `crate::` 引用的路径一致，因此源码无需改动。
// ─────────────────────────────────────────────────────────────────────────────
#[path = "src/format.rs"]
mod format;
#[path = "src/asm.rs"]
mod asm;
#[path = "src/crypt.rs"]
mod crypt;
#[path = "src/key.rs"]
mod key;
#[path = "src/algorithms/mod.rs"]
mod algorithms;

fn main() {
    // ── 依赖追踪：改任何一个生成器/格式/密钥都要重跑 ──
    for f in [
        "src/format.rs",
        "src/asm.rs",
        "src/crypt.rs",
        "src/key.rs",
        "src/algorithms/mod.rs",
        "src/algorithms/dominant.rs",
        "src/algorithms/downscale.rs",
        "src/algorithms/blur.rs",
    ] {
        println!("cargo:rerun-if-changed={f}");
    }
    println!("cargo:rerun-if-changed=ISA.md");

    // ── 生成三个加密程序 ──
    let dominant = protect("dominant", algorithms::dominant::build());
    let downscale = protect("downscale", algorithms::downscale::build());
    let blur = protect("blur", algorithms::blur::build());

    let mut out = String::new();
    out.push_str("// @generated by vmp/build.rs —— 请勿手改。\n");
    out.push_str("//\n");
    out.push_str("// 这里存放的是**加密后**的虚拟机程序。每个 blob 的布局：\n");
    out.push_str("//   [0..20]  明文头（magic / isa_version / code_len / const_count / checksum）\n");
    out.push_str("//   [20..]   ChaCha20 加密的载荷（常量池 + 字节码）\n");
    out.push_str("// 想验证「算法真的不在机器码里」，用 `strings`/`objdump` 看这个数组即可，\n");
    out.push_str("// 你会只看到一堆看不出结构的字节。\n\n");
    out.push_str(
        "/// 一个受保护的虚拟机程序。\n\
         ///\n\
         /// 字段都是 `&'static`，所以能放进 `static`（`Flags` 里的 `Vec` 不行，\n\
         /// 这里用切片存 `input_dims`，由 [`Program::flags`] 在启动时构造）。\n\
         pub struct Program {\n\
         \x20   pub name: &'static str,\n\
         \x20   /// 明文头 + 加密载荷。\n\
         \x20   pub blob: &'static [u8],\n\
         \x20   pub key: &'static [u8; 32],\n\
         \x20   pub nonce: &'static [u8; 12],\n\
         \x20   pub input_dims: &'static [u8],\n\
         \x20   pub out: u8,\n\
         }\n\n\
         impl Program {\n\
         \x20   /// 构造 VM 需要的元信息。\n\
         \x20   pub fn flags(&self) -> crate::format::Flags {\n\
         \x20       crate::format::Flags { input_dims: self.input_dims.to_vec(), out: self.out }\n\
         \x20   }\n\
         }\n\n",
    );

    for p in [&dominant, &downscale, &blur] {
        out.push_str(&format!(
            "/// `{}` 程序：输入维度 {:?}，输出段 {}，密文 {} 字节。\n\
             pub static {}: Program = Program {{\n\
             \x20   name: \"{}\",\n\
             \x20   blob: &{},\n\
             \x20   key: &{},\n\
             \x20   nonce: &{},\n\
             \x20   input_dims: &{:?},\n\
             \x20   out: {},\n\
             }};\n\n",
            p.name,
            p.dims.as_slice(),
            p.out,
            p.blob.len(),
            p.name.to_uppercase(),
            p.name,
            bytes_literal(&p.blob),
            bytes_literal(&p.key),
            bytes_literal(&p.nonce),
            p.dims.as_slice(),
            p.out,
        ));
    }

    out.push_str("/// 全部程序，供 JNI 层按名字查找。\n");
    out.push_str("/// 用 `&[&Program]`（引用数组）而不是 `&[Program]`：`Program` 值含 `[u8; 32]`，\n");
    out.push_str("/// 在 `static` 初始化器里按值放入数组会触发「move out of shared reference」。\n");
    out.push_str("pub static ALL: &[&Program] = &[&DOMINANT, &DOWNSCALE, &BLUR];\n");

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR 未设置")).join("programs.rs");
    fs::write(&dest, out).expect("写 programs.rs 失败");
}

/// 一个已加固程序的可生成信息。
struct Protected {
    name: &'static str,
    blob: Vec<u8>,
    key: [u8; 32],
    nonce: [u8; 12],
    dims: Vec<u8>,
    out: u8,
}

/// 加密一个明文容器：只加密 `[20..]`，再重算校验和。
///
/// 明文头（`[..20]`）保持可读是**有意的**，见 `ISA.md` 第 4 节：
/// VM 需要在不解密的前提下知道「载荷有多长、常量池多大」。
fn protect(name: &'static str, mut blob: Vec<u8>) -> Protected {
    assert!(
        blob.len() > format::HEADER_LEN,
        "{name} 程序为空 —— 生成器可能坏了"
    );
    let nonce = key::nonce_of(name).unwrap_or_else(|| panic!("{name} 没有登记 nonce"));
    crypt::apply_keystream(&key::MASTER_KEY, &nonce, &mut blob[format::HEADER_LEN..]);
    // 载荷现在是密文；校验和必须覆盖**密文**，否则 VM 不解密就没法验（见 format::seal）
    format::seal(&mut blob);

    // 元信息从生成器拿：这里重新调一次 prog.flags() 不可行（build() 只回 blob），
    // 故按名字查表 —— 与 `algorithms` 里的约定保持一致。
    let (dims, out) = match name {
        "dominant" => (vec![1, 4], format::out::WORK),
        "downscale" => (vec![1, 4, 4, 1, 1, 4, 1], format::out::DST),
        "blur" => (vec![1, 4, 4, 4, 4, 1], format::out::WORK),
        other => panic!("未登记的受保护程序: {other}"),
    };

    Protected {
        name,
        blob,
        key: key::MASTER_KEY,
        nonce,
        dims,
        out,
    }
}

/// 渲染成 `[1, 2, 3]` 形式的字面量。
fn bytes_literal(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 4 + 2);
    s.push('[');
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            s.push(',');
        }
        s.push_str(&b.to_string());
    }
    s.push(']');
    s
}
